Sprint #13 Add controllers
sabolenok/java-shareit pull request #1
Opened 2022-11-22 08:37 UTC by sabolenok

2022-11-23 20:54 UTC, sergeymamonov requested changes

2022-11-23 20:54 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/user/UserService.java
> +    public Collection<User> findAll() {
Collection слишком общий интерфейс, то есть можно передать и Set и List. На мой взгляд, интерфейс List более уместен, если предполагается возвращать массив юзером.

2022-11-23 20:54 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/user/UserStorageImpl.java
> +                throw new RuntimeException("Пользователь с таким email уже существует");
Лучше создать свою ошибку, но не RuntimeException (это слишком общая ошибка)

2022-11-23 20:54 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/exception/ErrorHandler.java
> +}
Можно добавить еще обработку не обрабатываемого исключения.

2022-11-24 06:50 UTC, sabolenok commented on src/main/java/ru/practicum/shareit/user/UserService.java
> +    public Collection<User> findAll() {
Поменяла на List

2022-11-24 06:51 UTC, sabolenok commented on src/main/java/ru/practicum/shareit/user/UserStorageImpl.java
> +                throw new RuntimeException("Пользователь с таким email уже существует");
Создано AlreadyExistEmailException

2022-11-24 06:51 UTC, sabolenok commented on src/main/java/ru/practicum/shareit/exception/ErrorHandler.java
> +}
Добавила обработку Throwable в ErrorHandler

2022-11-24 19:48 UTC, sergeymamonov approved these changes

2022-11-25 05:01 UTC, merged