#15 Add bookings
sabolenok/java-shareit pull request #2
Opened 2022-12-06 12:26 UTC by sabolenok

2022-12-07 06:02 UTC, sergeymamonov requested changes

2022-12-07 06:02 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +import java.util.*;
Лучше явно указывать импортируемые классы, а не через *

2022-12-07 11:56 UTC, sabolenok commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +    List<Comment> comments;
Пропущен случайно:) добавила

2022-12-07 11:56 UTC, sabolenok commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +                setBookingDates(item);
Исправлено

2022-12-07 11:57 UTC, sabolenok commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +import java.util.*;
Исправлено

2022-12-07 21:51 UTC, sergeymamonov approved these changes
Остались запросы в цикле к БД. Если не разберетесь, то обращайтесь.

2022-12-07 21:51 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +            Optional<User> foundUser = userRepository.findById(c.getAuthorId());
Здесь можно избавиться от цикла, если запрос сделать типа дай мне юзеров, у которых id в списке {}.
Получаем список юзером и соединяем его с комментариями.

2022-12-07 21:51 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +            setComments(item, comments);
Здесь тоже запрос в цикле, так как в методе setComments есть запрос в БД. То есть для каждой вещи мы обращаемся в БД. Нам цикл нужен здесь не для запросов, а для обработки результатов.

2022-12-08 05:25 UTC, sabolenok commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +            setComments(item, comments);
Вынесла получение списка юзеров вне метода setComments. Внутри setComments обрабатываем полученные заранее данные по юзерам, таким образом запроса в цикле больше нет

2022-12-19 13:06 UTC, merged