Add item requests
sabolenok/java-shareit pull request #3
Opened 2022-12-29 11:45 UTC by sabolenok

2022-12-29 20:29 UTC, sergeymamonov requested changes

2022-12-29 20:29 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/item/ItemMapper.java
> +        if (!(comments == null)) {
Можно проще comments != null

2022-12-29 20:29 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +                setBookingDates(item, bookings);
Этот метод вызывается в цикле, а в нем есть запросы в БД, то есть получается что в БД грузится большим количеством запросов. Это большая нагрузка на БД. Затратно по времени из-за передачи по сети. Как в данной ситуации можно уйти от цикла:
1. Выгружаем комментарии, группируем их по вещам и конвертируем в dto
2. Выгружаем подтвержденные бронирования отсортированные по дате начала и группируем их по вещам
3. Для каждой вещи находим последнее и следующее бронирование, а также комментарии и формируем результат

2022-12-29 20:29 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
>      }
Строка 249 я бы не пожалел букв for (Comment comment : comments)

2022-12-30 13:23 UTC, sabolenok commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +                setBookingDates(item, bookings);
При вызове метода внутри цикла, у меня уже передавалась коллекция Booking'ов, поэтому запроса в БД в цикле не было бы. Но претензия понятна, убрала.

2022-12-30 13:23 UTC, sabolenok commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +        if (from == null || size == null) {
Исправила, лишний метод из сервиса тоже убрала

2022-12-30 13:23 UTC, sabolenok commented on src/main/java/ru/practicum/shareit/item/ItemMapper.java
> +        if (!(comments == null)) {
Готово

2022-12-30 13:24 UTC, sabolenok commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
>      }
Готово

2023-01-03 06:30 UTC, merged